apiVersion: v1
kind: Service
metadata:
  name: {{ include "iedb-enterprise.readerHeadlessName" . }}
  labels:
    {{- include "iedb-enterprise.roleLabels" (dict "ctx" . "role" "reader") | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8000
    - name: coordinator
      port: 9100
  selector:
    {{- include "iedb-enterprise.roleSelectorLabels" (dict "ctx" . "role" "reader") | nindent 4 }}
